In [2]:
from datascience import *
import numpy as np

In [5]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba.show(5)

rank,name,position,team,salary
1,Stephen Curry,PG,Golden State Warriors,40231758
2,Chris Paul,PG,Oklahoma City Thunder,38506482
3,Russell Westbrook,PG,Houston Rockets,38506482
4,John Wall,PG,Washington Wizards,38199000
5,Kevin Durant,SF,Brooklyn Nets,38199000


In [6]:
nba.labels

('rank', 'name', 'position', 'team', 'salary')

In [9]:
PG = (nba.where('position','PG')
    .drop('position')
    .relabeled('salary','$'))
PG.show(5)

rank,name,team,$
1,Stephen Curry,Golden State Warriors,40231758
2,Chris Paul,Oklahoma City Thunder,38506482
3,Russell Westbrook,Houston Rockets,38506482
4,John Wall,Washington Wizards,38199000
8,Kyle Lowry,Toronto Raptors,34996296


In [10]:
PG.select('$')

$
40231758
38506482
38506482
38199000
34996296
32742000
32511624
31742000
29802321
20000000


In [11]:
PG.column('$')

array([40231758, 38506482, 38506482, 38199000, 34996296, 32742000,
       32511624, 31742000, 29802321, 20000000, 19894737, 19500000,
       19217900, 19000000, 16200000, 15643750, 15625000, 15500000,
       13437500, 12553571, 12428571, 12345680, 12000000, 10605600,
        9745200,  9607500,  9600000,  9473684,  9258000,  9133907,
        8730240,  8719320,  8113930,  8000000,  7317073,  7250000,
        6400920,  6392760,  6273000,  6000000,  5348007,  5307120,
        4855800,  4767000,  4764960,  4463640,  4444746,  3500000,
        3150000,  3000000,  3000000,  2564753,  2329200,  2321735,
        2147317,  2000000,  1948080,  1845301,  1737145,  1620564,
        1620564,  1620564,  1620564,  1620564,  1620564,  1620564,
        1620564,  1618520,  1588231,  1500000,  1445697,  1416852,
        1416852,  1416852,  1228026,  1052909,   898310,   898310,
         563347,   522738,   512721,   350189])

In [13]:
np.sum(PG.column('$'))

774094676

In [14]:
PG.column('$').item(0)

40231758

In [15]:
np.average(PG.column('$'))

9440178.975609757

In [17]:
make_array(0,1,2,3,4,5,6)

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [18]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [19]:
PG.take(1)

rank,name,team,$
2,Chris Paul,Oklahoma City Thunder,38506482


In [20]:
PG.take(1,3,0)

rank,name,team,$
2,Chris Paul,Oklahoma City Thunder,38506482
4,John Wall,Washington Wizards,38199000
1,Stephen Curry,Golden State Warriors,40231758


In [22]:
np.sum(PG.take(np.arange(6)).column('$'))

223182018

In [23]:
PG.select('name','team')

name,team
Stephen Curry,Golden State Warriors
Chris Paul,Oklahoma City Thunder
Russell Westbrook,Houston Rockets
John Wall,Washington Wizards
Kyle Lowry,Toronto Raptors
Kemba Walker,Boston Celtics
Mike Conley,Utah Jazz
Kyrie Irving,Brooklyn Nets
Damian Lillard,Portland Trail Blazers
Malcolm Brogdon,Indiana Pacers


In [26]:
capital = make_array('London','Pairs','Beijing','Washinton.DC','Berlin')
capital

array(['London', 'Pairs', 'Beijing', 'Washinton.DC', 'Berlin'],
      dtype='<U12')

In [25]:
Table()

In [27]:
country = make_array('UK','France','China','USA','Germany')
country

array(['UK', 'France', 'China', 'USA', 'Germany'],
      dtype='<U7')

In [34]:
powerful = Table().with_column('Country',country).with_column('Capital',capital)
powerful

Country,Capital
UK,London
France,Pairs
China,Beijing
USA,Washinton.DC
Germany,Berlin


In [31]:
powerful.with_column('Capital',capital)

Country,Capital
UK,London
France,Pairs
China,Beijing
USA,Washinton.DC
Germany,Berlin


In [56]:
gdp = make_array(4.00,3.37,19.50,30.77,5.05)

In [57]:
powerful = powerful.with_column('GDP',gdp)
powerful

Country,Capital,GDP
UK,London,4
France,Pairs,3.37
China,Beijing,19.5
USA,Washinton.DC,30.77
Germany,Berlin,5.05


In [58]:
powerful.sort('GDP',descending=True)

Country,Capital,GDP
USA,Washinton.DC,30.77
China,Beijing,19.5
Germany,Berlin,5.05
UK,London,4
France,Pairs,3.37


In [66]:
powerful = powerful.exclude([5,6])
powerful

Country,Capital,GDP
UK,London,4
France,Pairs,3.37
China,Beijing,19.5
USA,Washinton.DC,30.77
Germany,Berlin,5.05
Switzerland,Bern,1


In [68]:
powerful.with_column('Planet','earth')

Country,Capital,GDP,Planet
UK,London,4,earth
France,Pairs,3.37,earth
China,Beijing,19.5,earth
USA,Washinton.DC,30.77,earth
Germany,Berlin,5.05,earth
Switzerland,Bern,1,earth
